import { useMemo } from 'react';
import { TranscriptionBackend } from '../../shared/types';

const SUPPORTED_LANGUAGES = {
  af: 'Afrikaans',
  ar: 'Arabic',
  hy: 'Armenian',
  az: 'Azerbaijani',
  be: 'Belarusian',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  zh: 'Chinese',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  en: 'English',
  et: 'Estonian',
  fi: 'Finnish',
  fr: 'French',
  gl: 'Galician',
  de: 'German',
  el: 'Greek',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  is: 'Icelandic',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  kn: 'Kannada',
  kk: 'Kazakh',
  ko: 'Korean',
  lv: 'Latvian',
  lt: 'Lithuanian',
  mk: 'Macedonian',
  ms: 'Malay',
  mr: 'Marathi',
  mi: 'Maori',
  ne: 'Nepali',
  no: 'Norwegian',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  ro: 'Romanian',
  ru: 'Russian',
  sr: 'Serbian',
  sk: 'Slovak',
  sl: 'Slovenian',
  es: 'Spanish',
  sw: 'Swahili',
  sv: 'Swedish',
  tl: 'Tagalog',
  ta: 'Tamil',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
  cy: 'Welsh',
};

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

const LANGUAGES_BY_BACKEND: Record<TranscriptionBackend, LanguageCode[]> = {
  [TranscriptionBackend.OpenAIWhisper]: [
    'af',
    'ar',
    'hy',
    'az',
    'be',
    'bs',
    'bg',
    'ca',
    'zh',
    'hr',
    'cs',
    'da',
    'nl',
    'en',
    'et',
    'fi',
    'fr',
    'gl',
    'de',
    'el',
    'he',
    'hi',
    'hu',
    'is',
    'id',
    'it',
    'ja',
    'kn',
    'kk',
    'ko',
    'lv',
    'lt',
    'mk',
    'ms',
    'mr',
    'mi',
    'ne',
    'no',
    'fa',
    'pl',
    'pt',
    'ro',
    'ru',
    'sr',
    'sk',
    'sl',
    'es',
    'sw',
    'sv',
    'tl',
    'ta',
    'th',
    'tr',
    'uk',
    'ur',
    'vi',
    'cy',
  ],
};

export const useLanguages = (
  backend: TranscriptionBackend
): { languages: { code: LanguageCode; name: string }[] } => {
  const langs = useMemo(() => {
    const languages =
      LANGUAGES_BY_BACKEND[backend || TranscriptionBackend.OpenAIWhisper];

    return {
      languages: languages.map((code) => ({
        code,
        name: SUPPORTED_LANGUAGES[code],
      })),
    };
  }, [backend]);

  return langs;
};
